### ISSUE TITLE
Add curve448

### ISSUE THREAD

**Issue by yiatsec** [DSC-iTC/cPP#110]
**What is the change request for the cPP? Please describe.**
NIST SP 186-5 published on 2023-02-03, which approved EdDSA curve25519 and curve448. The DSC cPP v1.0 only allows curve25519 but not curve448.

**Describe the solution you'd like**
Please consider to include curve448 in DSC cPP v1.1.

**Comment by woodbe** [comment]
This is resolved as part of the crypto update as these are all included in the latest requirements.
