### ISSUE TITLE
desired updates to DSC cPP v1.0 and its SD

### ISSUE THREAD

**Issue by yiatsec** [DSC-iTC/cPP#118]
atsec found some typos and inconsistencies in DSC cPP (https://www.niap- ccevs.org/MMO/PP/cpp_dsc_v1.0.pdf) and its Supporting Document (SD) (https://www.niap-ccevs.org/MMO/PP/cpp_dsc_sd_v1.0.pdf). It would be great if they can be fixed in the next revision. 
1. DSC cPP Section 2.2.1: "A DSC protects the integrity of an SDO with one of the following methods:..." should be extended to allow authenticated encryption ciphers compliant to NIST SP800-38F such as AES Key-Wrapping and TDES Key- Wrapping.
2. SD section 4.1.1.2.1: FCS_COP.1/KDF is mentioned in paragraph 483, but this SFR does not exist in DSC cPP. We believe FCS_COP.1/KDF should be replaced with FCS_CKM_EXT.5.
3. SD section 4.1.3.1.3: the test for FCS_COP.1/PBKDF may require a NIST CAVP certificate because the algorithm testing for PBKDF is now available on the NIST ACVTS.
4. SD section 2.1.6.1.3: "common application developer" is mentioned in paragraphs 257 and 259 regarding the test requirements for FCS_STG_EXT.1, but the DSC cPP does not allow selection of "common application developer".
5. SD section 2.2.8.1.3: "FCS_COP.1/SK" should be replaced by "FCS_2.COP.1/SKC" in paragraph 313.
6. SD section 2.4.1.1.3: "FMT_SMF_EXT.1.1" should be replaced by "FMT_SMF.1.1" in paragraph 355.
7. SD section 2.5.4.1.3: "FPT_PHP.1" should be replaced by "FPT_PHP.3" as test requirement for FPT_PRO_EXT.1.

**Comment by woodbe** [comment]
The first one has been handled

**Comment by woodbe** [comment]
Crypto will be handled as part of crypto update, other editorial comments were handled in TD DSC0003.
