### ISSUE TITLE
[cPP CHANGE] references to the crypto algorithm validation system documents

### ISSUE THREAD

**Issue by yiatsec** [DSC-iTC/cPP#120]
For the DSC cPP v1.1, we need to update the references to the latest version of the crypto algorithm standards (e.g., FIPS 186-5) and the corresponding algorithm validation systems in the supporting document (SD). We should remove the references to RSA2VS/ECDSA2VS and other similar VSs from the future revision of the DSC cPP SD because they are obsoleted and will not be updated. Instead, we need to refer to the ACVP documents that are part of their github and they already mentioned 186-5:
https://github.com/usnistgov/ACVP/blob/master/src/rsa/sections/05-siggen-capabilities.adoc
https://github.com/usnistgov/ACVP/blob/master/src/ecdsa/sections/05-ecdsa-siggen-capabilities.adoc

The CAVP maintains a list of transitioning algorithms, and that includes 186-5 at the end of the table on the first tab here
https://csrc.nist.gov/Projects/cryptographic-module-validation-program/programmatic-transitions

**Comment by woodbe** [comment]
part of the CCDB crypto WG update

**Comment by woodbe** [comment]
Closing as the changes have been made
