### ISSUE TITLE
Should RSA be forced as selection for KEK?

### ISSUE THREAD

**Issue by woodbe** [DSC-iTC/cPP#135]
https://github.com/DSC-iTC/cPP/blob/5458098653a375680b3341cfe2bc89e34fb552e6/cPP_DSC.adoc?plain=1#L984

In this line it is mandated that the DSC must generate RSA keys and that all others are optional. While this is most likely, it doesn't seem to make sense to mandate RSA keys.

When updating the doc, it would seem that we should remove the "identifier AK1" part.

**Comment by smuellerDD** [comment]
The SFR in question specifies a selection to allow asymmetric keys to be used as KEK (and thus to be generated compliant to the SFR defining asym key generation). It does not require that the DSC provides this mechanism.

That said, asymmetric keys are legitimate to be used as KEKs. This is used as part of the Key Encapsulation Mechanisms (e.g. RSA key wrapping, or Kyber).

That said, I would recommend leaving the line untouched.

**Comment by woodbe** [comment]
@smuellerDD My point was that you could possibly use other asymmetric keys as KEKs (MDF for example provides the option to use ECC keys for Sensitive Data Protection). I agree that asymmetric keys should be kept here, but should the "identifier AK1" part be left which restricts asymmetric keys for KEKs to ONLY be RSA keys. That is my thought, that we should remove the specification that only AK1 keys can be used for this purpose.

**Comment by smuellerDD** [comment]
Am Donnerstag, 27. Juli 2023, 13:47:05 CEST schrieb Brian Wood:

Hi Brian,

> @smuellerDD My point was that you could possibly use other asymmetric keys
> as KEKs (MDF for example provides the option to use ECC keys for Sensitive
> Data Protection). I agree that asymmetric keys should be kept here, but
> should the "identifier AK1" part be left which restricts asymmetric keys
> for KEKs to ONLY be RSA keys. That is my thought, that we should remove the
> specification that only AK1 keys can be used for this purpose.

MDFPP allows the use of ECC keys to perform a DH operation whose shared secret 
is used to derive a symmetric key to perform a symmetric encryption. Thus, the 
ECC key is only very indirectly participating in the key encryption. The 
direct use of ECC keys for encryption is not specified to my knowledge.

That said, key-agreement-based KEKs are important. To my reading, however, 
they are already allowed.

Do I miss something here?

Ciao
Stephan

**Comment by woodbe** [comment]
Probably not, I just don't like restricting the options where it seems there may be places where someone can make a different choice. Is there a particular reason to not allow other options (beyond the "we don't know of anyone doing anything else at this time" argument)?

The vendor would still need to describe what they are doing and why, it just wouldn't be limited to that specific choice.

**Comment by jdonndelinger** [comment]
Given the move to new PQ asymmetric algorithms I agree that RSA should no
longer be mandated. It'll probably be around for a while for compatibility
with legacy systems, but there's a real push to get the PQ stuff out there.

~Jim
