### ISSUE TITLE
App note 62 (FTP_ITC_EXT.1) does not make sense

### ISSUE THREAD

**Issue by woodbe** [DSC-iTC/cPP#140]
There is no selection in either FTP_ITC_EXT.1 or FTP_ITC_EXT.2 that would actually bring this requirement in for use. While it could be manually specified in an assignment, it seems that this may have been changed at some point and this app note was not updated.

I'm not sure if this should be resolved by updating the FTP_ITC_EXT SFRs (that seems most likely) or something else. I'm not sure if there is some history I'm missing.

**Comment by smuellerDD** [comment]
Note 62 applies to F*D*P_ITC_EXT.1/2 and not FTP. In those SFRs I see "physically protected channels as specified in FTP_ITP_EXT.1". Thus all looks consistent to me.

What am I missing in respect to the question?

**Comment by woodbe** [comment]
Ok, I see, I was actually looking at the ECD which didn't have it and clearly didn't realize I was looking at the ECD instead of the actual SFR.
