### ISSUE TITLE
FDP_SDC_EXT.1 -> FCD_SDC.2

### ISSUE THREAD

**Issue by woodbe** [DSC-iTC/cPP#146]
Should review this possible change. It isn't a completely obvious switch, but it is close, and may be appropriate with the proper definitions (app notes, etc).

FDP_SDC.2.1
The TSF shall ensure the confidentiality of the [selection: all user data, the following user data [assignment: list of user data]] according to [assignment: data characteristics] while it is stored under the control of the TSF.
FDP_SDC.2.2
The TSF shall ensure the confidentiality of the user data specified in FDP_SDC.2.1 without user intervention.

**Comment by robertmclemons** [comment]
I don't see how to specify the data protection methods in FDP_SDC.2. That seems like it could be important. Maybe there is some Common Criteria voodoo involved.

**Comment by woodbe** [comment]
So here is what I would do for putting this in. I split the statement from the current requirement into the two assignments here. 

I actually do not think we need to specify the type of data protection method here. In the new catalog those are all specified already, so the vendor will need to choose them and use the appropriate ones for storage based on that. FCS_COP.1/KeyEncap and FCS_COP.1/KeyWrap along with the FCS_COP.1/SKC specifies all the allowed methods already, so the proper algorithms would already need to be specified there. 

Similarly for the key generation I don't see that this needs to be specified as it is already an SFR used for all key generation, so stating it here is duplicative.

We could add in the app note something about needing to make sure the methods used are clear, but I think that is sufficient for the purposes here. 
FDP_SDC.2.1
The TSF shall ensure the confidentiality of the [the following user data [assignment: _list of internally and externally stored SDEs_]] according to [assignment: _SDEs identified in the Confidential SDE List attribute of an SDO_] while it is stored under the control of the TSF.

FDP_SDC.2.2
The TSF shall ensure the confidentiality of the user data specified in FDP_SDC.2.1 without user intervention.

**Comment by woodbe** [comment]
@woodbe will work on creating a pull request.

**Comment by woodbe** [comment]
I made the PR just switching the ECD for the CC:2022.

I think if we want to consider merging this into the FCS_STG_EXT SFRs that we may need to tweak those SFRs such that they store SDEs and SDOs, not keys and secret data. I don't see this as a problem, but while some things related to key would still make sense, I think this change would need more thought. Moving FCS_STG_EXT to a more generic phrasing would probably be good since currently it is all about storing keys only, but keys are, at least in my thinking, either an SDE or SDE (depending on what it is, probably), so talking about things as SDEs/SDOs should be OK, but some of the specific items would need further tweaking and may have larger implications to how other SFRs are written (which I have not taken into account at this point).
