### ISSUE TITLE
FMT_MOF_EXT.1 -> FMT_LIM.1/2

### ISSUE THREAD

**Issue by woodbe** [DSC-iTC/cPP#147]
The new FMT_LIM.1 and FMT_LIM.2 could be used to describe the current FMT_MOF_EXT.1 instead of having the extended SFR.

This would require some explanation as to how it would plug in, but should be considered.

**Comment by woodbe** [comment]
This may be too much to change in terms of what it accomplishes, but this is what I think these SFRs would look like. I am using the same policy for both because I cannot see any benefit for making the policy any more complicated than that statement which provides both the capability (management functions) and the availability (limited to authenticated administrators).

FMT_LIM.1.1
The TSF shall limit its capabilities so that in conjunction with “Limited availability (FMT_LIM.2)” the following policy is enforced [_management functions are limited to authenticated administrators_].

FMT_LIM.2.1
The TSF shall be designed in a manner that limits its availability so that in conjunction with “Limited capabilities (FMT_LIM.1)” the following policy is enforced [_management functions are limited to authenticated administrators_].

**Comment by robertmclemons** [comment]
That might just work. Having just now taken a close look, it appears that FMT_MOF.1. is about managing the management functions, but not about restricting the ability to invoke them.

**Comment by woodbe** [comment]
Discussion on the call agreed to leave the SFR as it is.
