### ISSUE TITLE
cPP SFR tracking adjustments

### ISSUE THREAD

**Issue by woodbe** [DSC-iTC/cPP#154]
Notes on @woodbe review of SFRs since the crypto changes.

FCS_CKM.1 -> parsing from FDP_ITC_EXT.1/2 is not key generation. I don't know that this is really needed. I get that this is part of "parse", but I think that this actually confuses the SFR since they aren't generated, it is imported.
FCS_CKM.1/KEK -> It seems like covers all the FCS_CKM.1 actual key generation functions, so could easily just have the derived KEKs listed and have a single requirement for both.
FCS_CKM.2 (new SFR) -> I replaced the FCS_CKM.2 for establishment to this (while also adding FCS_CKM_EXT.7). It seems like this is needed and could replace the FDP_ITC_EXT.1/2 from FCS_CKM.1, which would clean up the SFRs
**FCS_CKM_EXT.3** -> this is in the catalog and not added, but it looks like this may be useful. As noted in #153, this could be the way to simplify some of the keystore requirements. There isn't an explicit analog in the current cPP, but it seems like this would clarify things. This also seems like it would resolve on of the questions about the change from FCS_COP.1/KeyEnc to the new SFRs.
**FCS_ETC_EXT.1** -> This isn't currently included in the update, but it seems like this would be needed to support the propagate function.
**FCS_ITC_EXT.1** -> This isn't currently included in the update, but it seems like this would be needed to support the parse function (from external).

Update:

FCS_COP.1/KeyEncap -> Selection-based, controlled from FCS_CKM.2
FCS_COP.1/KeyWrap -> Selection-based, controlled from FCS_CKM_EXT.3

**Comment by robertmclemons** [comment]
I agree that FCS_CKM.1/KEK can probably go. If we need selections to bring in FCS requirements, FCS_CKM.1/KEK is probably not the best way.

**Comment by robertmclemons** [comment]
I also agree that FCS_CKM.1 should not refer to parsing and it should be replaced by FCS_CKM.1/SKG and FCS_CKM.1/AKG. In general, I think the higher-level DSC-specific requirements should refer to the crypto primitives and not the other way around.

**Comment by robertmclemons** [comment]
Another thing, we can remove all the rows from the various FCS_CKM and FCS_COP tables if we don't think a DSC should support those things. Specifically, we can cut a lot of rows out of FCS_COP.1/SKC.

**Comment by robertmclemons** [comment]
Do we know when we'll need FCS_CKM.2 vs. FCS_CKM_EXT.7? Will all DSCs need both of these? FCS_CKM.2 was mandatory in the original DSCcPP, but should both of these be mandatory?

**Comment by robertmclemons** [comment]
I'm not sure it would do us much good to use FCS_ETC/ITC_EXT from the catalog. It doesn't support physically protected channels or encrypted data blobs. And I think we would have to recast our protocols using FTP_PRO.

**Comment by woodbe** [comment]
> Another thing, we can remove all the rows from the various FCS_CKM and FCS_COP tables if we don't think a DSC should support those things. Specifically, we can cut a lot of rows out of FCS_COP.1/SKC.

So I would expect XTS could be removed, but beyond that I am not sure (the modes and the reason to use them are not really my strength). I would probably leave this to later to do, basically get the updated catalog and then update it at that point instead of trying to do it now and remember when making the update to the published catalog.

**Comment by woodbe** [comment]
#155 will resolve the FCS_CKM.1/2 changes noted in https://github.com/DSC-iTC/cPP/issues/154#issue-1902103298

**Comment by woodbe** [comment]
@robertmclemons please take a look at the current edits in the working draft and #156 (which has all the changes we need at the moment, but some questionable language from the catalog). I think all the tracing has been resolved that will bring in the correct SFRs when needed for things like the encapsulation and wrapping once that pull request has been merged.

**Comment by robertmclemons** [comment]
I think we can cut most of the App Notes under CKM_EXT.3. Maybe leave the one about key storage/escrow.  The whole AppNote situation is somewhat confused in the catalog. Some are notes intended to guide PP developers in using the catalog, some are intended for ST Authors and should be carried forward into a PP, and others are really just for the CWG so they remember why they made certain decisions. This hasn't really been cleaned up, so we should feel free to do what we need to do make sure ST Authors understand what is expected of them.

**Comment by woodbe** [comment]
So the SFR lists the following key access methods. I don't think all of these are relevant, so here is what I think we should keep/delete:

- cryptographic key usage in cryptographic operations - this is fine
- cryptographic key archival - I think we should change this to "storage" and adjust the description in the app note
- cryptographic key backup - delete (don't think this is something we consider here for the key store)
- cryptographic key escrow - delete (see backup)
- cryptographic key recovery - maybe
- modifications to attributes of cryptographic keys - this is fine
- cryptographic key destruction - no idea. I get the description, but I don't know if we want to have this or not

Based on this I would remove the app notes for probably the three in the middle off hand, adjust the archival as noted and probably leave the others.
