### ISSUE TITLE
Introduction Roles description

### ISSUE THREAD

**Issue by woodbe** [DSC-iTC/cPP#176]
- Roles: particularly separation and necessity of administrator and administrator owner roles:#
  - Sounds somehow of zero trust where there are distributed permissions to foreign authority for integrated handled BlackBox components. 
  - Principally okay if there are posed clear reqs to foreign authority in form of a within manufacturing cycle integrated secure process. 
  - In section there cannot be read s.th. like this

**Comment by robertmclemons** [comment]
I find both the comment and the Roles section to be confusing. If we look at FMT_SMR .1, it very simply states that there are two roles.  In real life it might not be so simple, but these requirements deal only with two. (Although FMT_MSA.1 calls for a "list of roles," which seems odd.) I suggest searching on "role" throughout the document to make sure the term is used consistently.
