### ISSUE TITLE
Introduction Key hierarchy description

### ISSUE THREAD

**Issue by woodbe** [DSC-iTC/cPP#178]
- Key hierarchy: several essential parts might be missing here
  - Good: several types of keys are extensively explained together with separate boundaries. 
  - Though: 
    - There are too few words spoken about the KDFs and PKIs used for different keys. In reality it is very important where key is created particularly here where most obviously several authorities might be integrated in key hierarchy related sub processes.
    - Nothing is said about the separate algorithms, RNGs used and allowed for separate keys.
  - Out from cryptology related concept intermediate Key protection has not to occur always in practice. Although it is here required. Justification therefore cannot be found here.
  - Approach: 1 different key hierarchy per role should somehow be reviewed. This approach might get because increased complexity problematic in eval phase.

**Comment by woodbe** [comment]
So as far as the points about KDF/PKI and separate algorithms, this section is purely informative to lay out how this should work. It isn't specifying an exact architecture and as such should not specify algorithms or methods to be used within the expected hierarchy.

For the last one, I actually don't think we preclude there being multiple, separate hierarchies. It starts with "A DSC may have a key hierarchy or key chain..." and this is all informative, so even here it is stating there may be, but not required.

For the protection of intermediate keys, someone else will have to answer. @slpotte @DewSecGitHub @jdonndelinger any ideas? I will state though that again, this is a way to categorize keys, as noted in 2.4.2, another way is by usage, and these are really just specifying options and types of systems that are expected. As such in this example, intermediate keys are protected, but as this is an example, they are not required to be. Even the sentence states "should always be protected" which isn't mandatory (not "shall").

So I would be OK if we wanted to make some minor adjustments, but I think this is fine as it is and propose to close this issue.

**Comment by slpotte** [comment]
I agree with Brian.  This is an informative section.  We could add more material here, but this document should not be a tutorial on key management.  I concur with closing this.
