### ISSUE TITLE
FDP and data caching/history

### ISSUE THREAD

**Issue by woodbe** [DSC-iTC/cPP#187]
Requirements in context of user data caching or and holding history is missing here but also elementary as also they provide vulnerability potential

**Comment by woodbe** [comment]
Contextually, this doesn't seem specifically relevant to the DSC. This seems like a requirement from a higher-level device (i.e. the device that contains the DSC), and there it is important. For the DSC though, there are several possible answers:

1. In the DSC all the "cached" data is basically coming from an SDE, and as such once opened, any resulting data would have to be cleared as part of FCS_CKM.6 once it is no longer needed, and so there isn't anything that is cached.
2. The DSC provides hardware protection for key storage along with a lot of authentication (and authorization) protections. So gaining general, broad access to the DSC such that you would see cached data or history would mean other, more important protections have already been broken, so by the time this is a concern, it really doesn't matter since larger issues have already broken the TOE

One possible consideration here is that we should probably modify FCS_CKM.6 to not just be about destroying cryptographic keys, but should modify that to be SDOs and SDEs, which automatically encompasses keys as we have those already defined as such. I think this is something we should look at doing.

**Comment by slpotte** [comment]
I think FCS_CKM.6 is enough and should not be extended to non-secret security attributes or metadata.  Sensitive user data such as PINs, passwords, authorization values, etc. are already covered by FCS_CKM.6.  No other action is necessary here, unless you want to add an app note to FDP_ITC_EXT.1 and .2 that the DSC is expected to destroy cryptographic keys and associated sensitive values with FCS_CKM.6.  It appears this is already in the dependency chart.  Is that enough?

**Comment by woodbe** [comment]
I'm OK to close this on the next call. If anyone else has a different opinion, please comment.

**Comment by woodbe** [comment]
Closing based on call discussion in agreement with above comments.
