### ISSUE TITLE
FMT_MSA.1.1 App Note 29

### ISSUE THREAD

**Issue by woodbe** [DSC-iTC/cPP#194]
The TSF vendor may pre-install SDOs… ‚
- This aspect comes too short. Either pre-installation is allowed and a lot of more rules and conditions have to be fulfilled from side of vendor and the administrator or this possibility should be removed. Requirement of specification of the pre-installed SDOs is by far not enough in this whole context. 
  - One example: What happens in case of dependency that means s.th. has to be changed in pre-installed SDO but administrator must not do so? Who discovers this necessity and who is in charge to solve that tricky situation?

**Comment by woodbe** [comment]
I think that this has to be answered by clarifying some aspects of the roles and then making sure the language is consistent. I get that what is being said can be tricky, but I'm not sure we are actually dealing with that specific scenario at all, and not sure that I want to try and bring it in here now.

I'm going to mark this as introduction to be handled as part of that update.

**Comment by slpotte** [comment]
We assumed that manufacturers provisioned the pre-installed SDOs.  These are typically necessary for management of manufacturer firmware.  Owner admins, on the other hand, typically do not produce and sign manufacturer firmware.  However, they may authenticate it and authorize its installation.  So, in this case, they can use the manufacturer SDOs, but may not be authorized to make changes to them.  Clarification of roles will help here.  We will probably discuss this more during a future call.

**Comment by woodbe** [comment]
I have made a small change to try and point out that the ability of the admin roles to modify the attributes should be specified.
