### ISSUE TITLE
FPT_MOD_EXT.1 other modes?

### ISSUE THREAD

**Issue by woodbe** [DSC-iTC/cPP#197]
You forgot to include here most important recovery or backup mode that is in practice often coubled to debug mode. Is recovery mode allowed? If so is really excluded that from there different boot mode can be reached? If not you should maybe add this to this section

**Comment by woodbe** [comment]
I think this can be closed here unless we want to bring in a number of requirements around how to enable/secure debug modes. The original determination was that debug would not be available, I do not see any particular reason to change that choice, especially since this is a product that is bundled inside a larger one, such that directly enabling a debug capability on a subcomponent within a larger product seems to be extremely tricky.

**Comment by slpotte** [comment]
Brian, I agree.  Debug modes may be allowed in development versions of firmware or software.  They should be discouraged for production versions.
