### ISSUE TITLE
FIA_AFL_EXT.2 locked SDO

### ISSUE THREAD

**Issue by woodbe** [DSC-iTC/cPP#203]
In case of use case ‚locked SDO‘: is there really any administrator to do so even administrators that do have only access to their pre-installed SDO’s. Might this not be problematic in real world?

**Comment by woodbe** [comment]
I do not have the history to properly answer this question. I understand how it would link together and work, but do not know the mechanics of how this would work in a DSC.

**Comment by slpotte** [comment]
We can make this a selection: "... then [strikethrough "only an administrator", add "[selection: administrator, owner of the object]"] may unlock access ...".

We may add an app note:  Users with authorization to use an object may be different from the owner of the object.  Administrators may not always have the permissions necessary to make modifications to objects they do not own.

**Comment by woodbe** [comment]
OK, on further reading of this right now I think we can just leave it. I'm not arguing that this could cause problems, but making that selection also mandates bringing in FIA_AFL_EXT.2 which, while it doesn't really provide any specific guidance, forces a description of how this would work. It really comes down to the vendor design. If they choose it, I would assume they have a way to make it work (and maybe it is meant to be painful, I don't know), otherwise they can skip it. If this was a forced option I would be more concerned about changing it, but since it is one of four options, I think we are OK leaving it in for now.

I propose to close this issue.

**Comment by woodbe** [comment]
Closed based on agreement with comments on call.
