### ISSUE TITLE
FIA_UAU.6 should not be numbered list

### ISSUE THREAD

**Issue by woodbe** [DSC-iTC/cPP#219]
Based on how that SFR is written, the numbered list should be a bulleted list.

Also, there isn't an option for "none", so it seems that on reading this reauth is ALWAYS forced in some manner, but FMT_MSA.3 implies that "none" is allowed as an option, so it seems like these are in conflict (maybe).

**Comment by slpotte** [comment]
There are too many words in this SFR.  Let's cut the conditions down to:

- none
- each access
- according to the policy in SDO.Reauth
