### ISSUE TITLE
"Concatenated keys" in FCS_CKM.5

### ISSUE THREAD

**Issue by yiatsec** [DSC-iTC/cPP#228]
Table 20 specifies the selection options of FCS_CKM.5. The term "Concatenated keys" in this table is confusion. 

Per NIST SP 800-108 (https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-108r1.pdf), the input to a KDF is the concatenation of the input key K_in, Label, Context, and the requested length L of the derived keying material K_out. I assume the "Concatenated keys" refers to the concatenation of the the K_in with the other components to form the input for a KDF. "Concatenated keys" if confusing because it could imply multiple keys are concatenated, which is not the case here.

I'd suggest to replace "Concatenated keys" with "input key and auxiliary strings."

**Comment by woodbe** [comment]
As this was taken from the crypto catalog, I suggest we wait for the next update to the catalog to be sent over and then see what may need to be done. In the meantime @jdonndelinger please take this feedback to the working group on the catalog for consideration in the revisions you are doing there.

**Comment by woodbe** [comment]
@woodbe will review the current catalog and see if this is still needed and provide response (or PR)

**Comment by woodbe** [comment]
So this is still in the catalog in the same way. @slpotte what do you think about this? Is it possible that your expectation in the catalog isn't actually a good match for the DSC?

**Comment by slpotte** [comment]
@woodbe, for FCS_CKM.5 we really meant two different keys contributed from two different sources.  I've added this as the third paragraph to the App Note to help clarify:  

Under input parameters, if concatenated keys or intermediary keys is selected, the ST Author should describe the sources of the keys, and the order in which they are concatenated, along with any other values that are concatenated with them.  This option may be chosen in instances when input keying material for the KDF comes from two independent sources, for example, a client and a server.
