### ISSUE TITLE
Add phrase to FCS_CKM_EXT.7.1 App Note 5

### ISSUE THREAD

**Issue by JDavid-Thompson** [DSC-iTC/cPP#239]
In Para 3, suggest adding "and there are two parties" to the parenthetical so it reads "(e.g., if each share is 128 bits and there are two parties, then the result after concatenation is a 256-bit key, which is appropriate only for AES-256-CMAC)"

In Para 4, suggest changing “For the KDF functions and XOR, each party may have to use an asymmetric method from FCS_CKM_EXT.7 to transmit their shares to each other” to “For the KDF functions and XOR, each party must transmit their shares securely, either by encrypting with an asymmetric method from FCS_CKM_EXT.7 or by procedural means, such as sending them by courier.”

**Comment by JDavid-Thompson** [comment]
Brian,

I think I made a pull request for #239.  I’m still a little unsure of all the github terms and operators.

-Dave

**Comment by woodbe** [comment]
I saw it

**Comment by woodbe** [comment]
@woodbe will review the current crypto catalog and provide a response here (or a PR)

**Comment by woodbe** [comment]
The second proposed change has been already updated (differently) in the catalog, and that text actually makes more sense.
