### ISSUE TITLE
FCS_RBG.1.1 

### ISSUE THREAD

**Issue by JDavid-Thompson** [DSC-iTC/cPP#240]
Suggest changing: “[selection: RBG algorithm]” to “[selection: DRBG algorithm]”   and changing the heading for Column 2 of Table 9 to “DRBG Algorithm”   and adding "Deterministic" before "Random" in the caption to Table 9.

**Comment by woodbe** [comment]
This was taken from CC:2022 directly, and is inclusive of both DRBGs as well as TRBGs (or whatever you want to call hardware-based sources that are not DRBGs). Changing it to DRBGs would exclude hardware-based sources.

**Comment by JDavid-Thompson** [comment]
Brian,

I don’t fully understand your response.

FCS_RBG.1.1 is only about the DRBG part of a TRBG.  The source of seeds is specified in subsequent SFRs.

The Table 9 caption says the table contains the supported methods for Random Bit Generation, but instead it contains  methods for Deterministic Random Bit Generation.  I was just trying to make the labels consistent.

How do my suggestions eliminate hardware DRBGs?

-Dave

**Comment by JDavid-Thompson** [comment]
OK.  Thanks.
