### ISSUE TITLE
FVS_OTV_EXT.1.1, App Note 11

### ISSUE THREAD

**Issue by JDavid-Thompson** [DSC-iTC/cPP#241]
First para, last sentence: suggest changing “importing and use” to “importing and using” or some other re-wording.

**Comment by woodbe** [comment]
This was taken from the CCDB working group text. The version this is based on is v0.1, and we are still waiting for the "final" version. At that point it would make more sense to consider whether to change the text than to do so now.

**Comment by woodbe** [comment]
This has been updated and the text is no longer there.

Closing
