### ISSUE TITLE
Appendix F: SFR Architecture, Table 26.

### ISSUE THREAD

**Issue by JDavid-Thompson** [DSC-iTC/cPP#242]
The text says there are seven services in Table 26, but there are eight, unless “TSF Security” doesn’t belong in the table (it doesn’t start with ‘P’).

Suggest updating the count to "eight", removing extra entries (if that is the case), or omitting the table size from the lead in.

**Comment by woodbe** [comment]
Checking on this, the description states it implements all 7 plus self-protection, so this is as it should be. This table was created in the 1.0, and is really just a reference to how the introduction describes the TOE compared to the SFRs. It is informative text and matches up with what was previously included.
