### ISSUE TITLE
Missing references in "Section 7 References"

### ISSUE THREAD

**Issue by JDavid-Thompson** [DSC-iTC/cPP#246]
Some references used in the SD are not defined in "Section 7 References", such as [SA] [GD] [GP_ROT] [NIST-ROTM] [ISO 24759].  They are defined in the cPP, however.  They should be transferred to the SD, or, better yet, a common bibliography could be built in a separate file and included into each document.

**Comment by woodbe** [comment]
This is what #109 is for. Once we are basically done (so we know what all the references should be), we will review and make sure they are all properly covered.
