### ISSUE TITLE
Should FCS_CKM.2 be selection or optional?

### ISSUE THREAD

**Issue by woodbe** [DSC-iTC/cPP#249]
The original FCS_CKM.2 was for Key establishment, but the new FCS_CKM.2 is key distribution. It doesn't seem that all modules must do this. Likely, yes, but I do not think that it is mandatory for all modules. I'm not sure how it should be placed, and how it gets pulled in exactly, since I would prefer selection-based to optional.

**Comment by woodbe** [comment]
As a related point, it would seem beneficial to change "key encapsulation" to be "key encapsulation as specified in FCS_COP.1/KeyEncap" which would explicitly bring in that requirement instead of doing it as part of the app note.

**Comment by slpotte** [comment]
I agree with Brian's proposal to add "... as specified in FCS_COP.1/KeyEncap".

**Comment by woodbe** [comment]
Call on 2/29, leave FCS_CKM.2 should be left as mandatory right now.

Add the referral.
