### ISSUE TITLE
FPT_PRO_EXT.2 Tests don't make sense

### ISSUE THREAD

**Issue by woodbe** [DSC-iTC/cPP#284]
The SD states that for this SFR testing of FDP_ITC_EXT and FMT_MSA.3 suffice. That doesn't make any sense given that the FDP_ITC_EXT SFRs are about importing and verifying the integrity of an SDE/SDO, which while similar, say nothing about how the measure is generated, only about how it would be imported and its integrity verified. This seems like an assumption that there is already something good? The FMT_MSA.3 actually doesn't have a test itself but refers to other tests to be done, so that linkage seems to be poor (and again unclear since that is about how things are set up).

Maybe it is OK to say that the FDP_ITC_EXT tests are OK and remove the FMT_MSA.3, but I think then there needs to be some justification as to why this is sufficient.

Lastly, some of this would seem like KMD, not TSS (since generally exactly what is done for integrity stuff related to RoT isn't made fully public), so maybe some guidance about what is expected in each place?

**Comment by woodbe** [comment]
So this whole SFR really seems to be about having a RoT Integrity service, which based on the app note in the cPP is included as part of the RoT Storage service automatically and hence isn't called out (since Storage is defined as RoT Confidentiality and RoT Integrity).

I actually think that this leads to a broader set of changes to properly resolve this:

- FPT_ROT_EXT.2 needs to be changed
  - The current SFR says the RoT will prevent unauthorized access. That isn't a function of a RoT, so the requirement actually makes no sense
  - The SFR should be updated to incorporate FPT_PRO_EXT.2 requirements along with some similar requirements for confidentiality
    - I do not have an idea as to what this would look like right now, but this SFR should have something about this
- FPT_PRO_EXT.2 is deleted
  - This SFR is actually not in the right place anyway. Since it is about RoT Integrity, it needs to be mandatory as that is part of the mandatory RoT Storage, so having it as optional actually does not make sense

**Comment by smuellerDD** [comment]
Am Freitag, 3. Mai 2024, 14:57:19 MESZ schrieb Brian Wood:

Hi Brian,

> So this whole SFR really seems to be about having a RoT Integrity service,
> which based on the app note in the cPP is included as part of the RoT
> Storage service automatically and hence isn't called out (since Storage is
> defined as RoT Confidentiality and RoT Integrity).
> 
> I actually think that this leads to a broader set of changes to properly
> resolve this:
> 
> - FPT_ROT_EXT.2 needs to be changed
>   - The current SFR says the RoT will prevent unauthorized access. That
> isn't a function of a RoT, so the requirement actually makes no sense

I concur with you, but I see no place in the PP where there are storage-
related SFRs that help here. As RoT's can be stored in immutable storage, the 
requirement is a function of the storage. Since we lack that, I feel like this 
SFR is the best choice to keep this requirement.

> - The
> SFR should be updated to incorporate FPT_PRO_EXT.2 requirements along with
> some similar requirements for confidentiality 

I would rather thing that the FPT_PRO_EXT.2 should be mandatory if the storage 
is mutable. Otherwise the SFR is not required.

> - I do not have an idea as to
> what this would look like right now, but this SFR should have something
> about this

> - FPT_PRO_EXT.2 is deleted
>   - This SFR is actually not in the right place anyway. Since it is about
> RoT Integrity, it needs to be mandatory as that is part of the mandatory
> RoT Storage, so having it as optional actually does not make sense

I do not fully agree here. A RoT can also be immutable based on technology. A 
lot of systems contain the RoT in ROM or OTP-Fuses. Thus, a service for 
integrity verification does not seem to be relevant at all.

Only when you have an mutable RoT, then I think your concern is warranted as 
it is *required*.

Ciao
Stephan

**Comment by woodbe** [comment]
The summary of the call discussion is that we will look to provide wrapping text such that it is clear how this does (or doesn't) relate to RoT Storage so the linkage is clean. That minimizes the changes overall, and ideally may leave just some test changes here for clarity, but nothing more broad.

@jvdsn will look to provide a pull request for the proposed text, after which the SD will be evaluated for necessary changes.

If this slips to Proposed Draft that will be fine.
