### ISSUE TITLE
Crypto WG questions

### ISSUE THREAD

**Issue by woodbe** [DSC-iTC/cPP#307]
FCS_COP.1/KeyWrap

For KW and KWP, the CAM algorithm has been removed, yet for the key sizes and the standards it is still listed for each one. Is there a reason for the mismatch?

[SP: There’s a lot of mismatch in this table.  We will have to go back and fix it.  If there is a corresponding ISO document, then the option stays; otherwise we will remove the option.]

**Comment by woodbe** [comment]
FCS_COP.1/KeyWrap

Is CCM & GCM really needed here since FCS_COP.1/AEAD is now explicit? While I can understand putting it here, it seems like any SFRs that may rely on GCM or CCM could just also point to the AEAD SFR in addition to KeyWrap.

**Comment by woodbe** [comment]
I think that I will leave the CCM/GCM off from our cPP and adjust requirements to point to the AEAD SFR instead of duplicating the requirements in multiple places.

**Comment by woodbe** [comment]
FCS_RBG.1, the HMAC list of standards seems to have issues with the selection closing brackets. Looking at the HASH, then the brackets should be after the "[SHA]", but for HMAC it is after the "10.1.2".

In the cPP I have placed it in the same place as the HASH.

**Comment by woodbe** [comment]
ISO/IEC 9797-2:2011 has been withdrawn, the current versions is [ISO/IEC 9797-2:2021](https://www.iso.org/standard/75296.html).

Should this be updated?

**Comment by slpotte** [comment]
I will forward the suggested changes to the Crypto Working Group
