### ISSUE TITLE
[cPP PUBLIC REVIEW] 

### ISSUE THREAD

**Issue by JDavid-Thompson** [DSC-iTC/cPP#309]
**What is the location of the document where the comment is made?**
Section 2.2, End of third paragraph.

**Comment Type.**
S = Substantial: a comment or issue significant enough to warrant a possible objection if the change (or a similar objective) is not met.

**What is the comment? Please describe.**
The statement about SoC makes it sound like the TOEs must be SoCs, not just that they could be. 

**Describe the proposed solution/edit**
 Suggest deleting “are integrated into a System on Chip (SoC) and as such”.

**Comment by woodbe** [comment]
Change the whole paragraph to something like this below (wordsmith the bullets)

Some examples of a DSC could be:

- A DSC may be comprised of a single embedded component within a device, such as a Secure Enclave Processor (SEP) or an SoC, 
- a multi-component system comprised of a software layer and several hardware components (which may be discrete or embedded), such as a Trusted Execution Environment (TEE). 
- Other configurations are possible, with the key point being the DSC is embedded within a larger system and is not a discrete component. 

These dedicated hardware/software components are isolated components of a larger physical package. <<ExofTOEInt>> below shows a block diagram of a typical example of a DSC TOE with all of its internal components.
