### ISSUE TITLE
CCDB AU/001 - Section 2.2 TOE Overview

### ISSUE THREAD

**Issue by woodbe** [DSC-iTC/cPP#31]
### Comment:
The paragraph just below Figure 1 has text “against SDEs/SDOs in memory and across restricted interfaces”.  Figure 1 hints that that “memory” can be outside the TOE.  Figure 2 on the next page (p13) hints that memory can be inside the TOE boundary.  In Section 2.4.5 it is made clear that SDEs/SDOs can exist inside or outside the TOE.

### Proposal:
Consider text in Section 2.2 that makes it clearer where the SDEs/SDOs can reside, perhaps something like: “against SDEs/SDOs in memory inside the TOE boundary and memory outside the TOE boundary”

### Priority: 2

**Comment by woodbe** [comment]
Agreed with clarification. As this is informative text though, can be moved to v1.1.

**Comment by woodbe** [comment]
On reading this again, I think that this can be ignored. The term here used in section 2.2 is specifically "memory" while the comparison in 2.4.5 is "protected storage". These are not the same, but at times may be read as such at times. I think adding clarification to 2.2 would actually make it more difficult to read, and the proper use of terms I think means this is not actually needed.

Recommendation to close this issue.

**Comment by yiatsec** [comment]
I'd suggest to replace "against SDEs/SDOs in memory and across restricted interfaces" in section 2.2 with "against SDEs/SDOs within the TOE and outside the TOE across restricted interfaces".
