### ISSUE TITLE
PBKDF2 question to be resolved

### ISSUE THREAD

**Issue by woodbe** [DSC-iTC/cPP#313]
https://github.com/DSC-iTC/cPP/pull/308#discussion_r1629833539

Review and discuss whether the DSC should allow for more options than are allowed by the crypto catalog.

**Comment by jvdsn** [comment]
A couple of references to PBKDF2 being used for password hashing purposes:
- OWASP: https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html
- NIST SP 800-63B: https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-63b.pdf ("Key derivation functions take a password, a salt, and a cost factor as inputs then generate a password hash. Their purpose is to make each password guessing trial by an attacker who has obtained a password hash file expensive and therefore the cost of a guessing attack high or prohibitive. Examples of suitable key derivation functions include Password-based Key Derivation Function 2 (PBKDF2) [SP 800-132] and Balloon [BALLOON].")
