### ISSUE TITLE
[cPP PUBLIC REVIEW] atsec07 - FCS_ITC_EXT.1

### ISSUE THREAD

**Issue by jvdsn** [DSC-iTC/cPP#325]
**What is the location of the document where the comment is made?**
Several occurences

**Comment Type.**
S = Substantial: a comment or issue significant enough to warrant a possible objection if the change (or a similar objective) is not met.

**What is the comment? Please describe.**
SFR FCS_ITC_EXT.1 appears in cPP. But this SFR is not defined.

**Describe the proposed solution/edit**
I'm not sure, is this just a simple typo? If so, FTP_ITC_EXT.1 or FDP_ITC_EXT.1?

**Comment by woodbe** [comment]
This came from the crypto catalog. It can be removed. There is still a remaining reference in the latest catalog (in the FCS_OTV_EXT.1 app note), but we can just take this out.
