### ISSUE TITLE
[cPP PUBLIC REVIEW] atsec21 - extended component definition formatting

### ISSUE THREAD

**Issue by jvdsn** [DSC-iTC/cPP#334]
**What is the location of the document where the comment is made?**
Appendix C

**Comment Type.**
A = Administrative: the issue is not significant enough to warrant an objection to the cPP if it isn't changed.

**What is the comment? Please describe.**
Editorial. As to formatting conventions, it is stated in cPP that "formatting conventions for selections and assignments in this Appendix are those in [CC2]."

In both CC v3.1 and CC:2022, the assignment and selection operations are presented in italicized text. Some extended SFRs defined in cPP Appendix C, e.g., the FCS_STG_EXT.1, FDP_ITC_EXT.2, use underlined texts.

**Describe the proposed solution/edit**
Investigate if the formatting needs to match CC2022 and if so, change the ECD.

**Comment by woodbe** [comment]
Summary from call: 

- Focus on the ECD first, determine scope of changes (probably just create a pull request). 
- Work on determining if, what and how much may need to change in the SFRs themselves for consistency (this could be shunted to later, depending on actual work)
