### ISSUE TITLE
[cPP PUBLIC REVIEW] [atsec11] SFR formatting

### ISSUE THREAD

**Issue by jvdsn** [DSC-iTC/cPP#378]
> In many SFRs, the key word "selection" and "assignment" should be bolded.

We have discussed this before in the context of the ECD. We didn't extend that effort to the full cPP, is that something we want to target for the 2.0 release?

**Comment by woodbe** [comment]
If I recall correctly, we needed to take out the bold on those (unless it made sense because of how the assignment was supposed to be?). I don't remember anything else, though, clearly we should have created an issue for it to track.
